[build]
  command = "npm run build"
  publish = "dist"
  environment = { NETLIFY_ENV = "production" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "no-store, no-cache"
